export const DUMMY_DATA = [
  {
    id: 1232,
    date: '20-1-2024 18:27:55',
    name: 'CTO Cihan Yıldız',
    status: 'new',
    requestType: 'Problem',
    requestMessage: "Skype doesn't work!",
    note: 'message',
  },
  {
    id: 4562,
    date: '22-1-2024 18:27:55',
    name: 'Erhan Akkaya',
    status: 'new',
    requestType: 'Help',
    requestMessage: 'Computer breakdown!',
    note: 'message',
  },
  {
    id: 7892,
    date: '24-1-2024 18:27:55',
    name: 'Cafer Uslu',
    status: 'on-hold',
    requestType: 'Problem',
    requestMessage: 'Irritating voices!',
    note: 'message',
  },
  {
    id: 9993,
    date: '24-1-2024 18:27:55',
    name: 'Halit Yıldız',
    status: 'closed',
    requestType: 'Problem',
    requestMessage: 'Irritating voices!',
    note: 'message',
  },
];
