export const DUMMY_DATA = [
  {
    id: 123,
    date: '25-1-2024 18:27:55',
    name: 'CTO Cihan Yıldız',
    status: 'open',
    requestType: 'Software and hardware issues',
    requestMessage: "Skype doesn't work!",
    note: 'message',
  },
  {
    id: 4562,
    date: '24-1-2024 18:27:55',
    name: 'Erhan Akkaya',
    status: 'new',
    requestType: 'Connectivity problems',
    requestMessage: 'Computer breakdown!',
    note: 'message',
  },
  {
    id: 7892,
    date: '23-1-2024 22:00:55',
    name: 'Cafer Uslu',
    status: 'on-hold',
    requestType: 'Network issues',
    requestMessage: 'Irritating voices!',
    note: 'message',
  },
  {
    id: 9993,
    date: '23-1-2024 15:00:55',
    name: 'Halit Yıldız',
    status: 'closed',
    requestType: 'Problem',
    requestMessage: 'Irritating voices!',
    note: 'message',
  },
  {
    id: 4279,
    date: '23-1-2024 15:00:55',
    name: 'Yağmur Köse',
    status: 'new',
    requestType: 'Problem',
    requestMessage: 'Irritating voices!',
    note: 'message',
  },
];
